name: Matrix Scraper

on:
  workflow_dispatch:
   
permissions:
  contents: write

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        state: [ca, ia, ny]
    steps:
      - name: Hello world
        run: echo "Scraping data for ${{ matrix.state }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install scraper
        run: pip install warn-scraper

      - name: Scrape
        run: warn-scraper ${{ inputs.state }} --data-dir ./data/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.state }}
          path: ./data/${{ matrix.state }}.csv  

  commit:
      name: Commit
      runs-on: ubuntu-latest
      needs: scrape
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            pattern: '*'
            path: artifacts/

        - name: Move
          run: |
            mkdir data -p
            mv artifacts/**/*.csv data/

        - name: Save datestamp
          run: date > ./data/latest-scrape.txt    

        - name: Commit and push
          run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@users.noreply.github.com"
            git add ./data/
            git commit -m "Latest data" && git push || true

            
    
